### PR TITLE
Various non-critical fixes

### LINKED ISSUE #206: 4.95.0: compile time warnings
First summary stats:
```console
[tkloczko@devel-g2v SPECS]$ rpmbuild -ba lsof.spec --quiet 2>&1 | grep -- \\[-W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
     29 -Wunused-variable
      2 -Wunused-value
      1 -Wparentheses
```
And extracted warnings
```console
util.c:40:13: warning: 'copyright' defined but not used [-Wunused-variable]
   40 | static char copyright[] =
      |             ^~~~~~~~~
In file included from node.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
node.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from store.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
store.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from dstore.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dstore.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from dfile.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dfile.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from dmnt.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dmnt.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from dnode.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dnode.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from usage.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
usage.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from misc.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
misc.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from proc.c:38:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
proc.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
print.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
In file included from main.c:40:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
main.c:35:13: warning: 'copyright' defined but not used [-Wunused-variable]
   35 | static char copyright[] =
      |             ^~~~~~~~~
In file included from dproc.c:37:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dproc.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
arg.c: In function 'ck_file_arg':
arg.c:481:31: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  481 |             if (!ss & ErrStat == 0)
      |                       ~~~~~~~~^~~~
arg.c: At top level:
arg.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
dsock.c: In function 'process_netsinfo':
dsock.c:1569:24: warning: unused variable 'tp' [-Wunused-variable]
 1569 |         struct tcp_udp*tp;              /* temporary INET socket info pointer */
      |                        ^~
dsock.c: In function 'process_nets6info':
dsock.c:1721:25: warning: unused variable 'tp' [-Wunused-variable]
 1721 |         struct tcp_udp6*tp;             /* temporary INET6 socket info pointer */
      |                         ^~
dsock.c: In function 'get_tcpudp':
dsock.c:78:52: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   78 |                                       + (tp)->laddr,                    \
      |                                                    ^
dsock.c:2999:29: note: in expansion of macro 'TCPUDP_IPC_HASH'
 2999 |                     int i = TCPUDP_IPC_HASH(tp);
      |                             ^~~~~~~~~~~~~~~
dsock.c: In function 'get_tcpudp6':
dsock.c:92:79: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   92 |                                        + TCPUDP6_IPC_ADDR_MK_INT(&(tp)->laddr), \
      |                                                                               ^
dsock.c:3376:29: note: in expansion of macro 'TCPUDP6_IPC_HASH'
 3376 |                     int i = TCPUDP6_IPC_HASH(tp6);
      |                             ^~~~~~~~~~~~~~~~
In file included from dsock.c:38:
lsof.h: At top level:
lsof.h:328:20: warning: 'dummy_utmp' defined but not used [-Wunused-variable]
  328 | static struct utmp dummy_utmp;          /* to get login name length */
      |                    ^~~~~~~~~~
dsock.c:33:13: warning: 'copyright' defined but not used [-Wunused-variable]
   33 | static char copyright[] =
      |             ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by masatake**
Close #206.

I introduced -Wall option in this pull request.
As the result, we'll get more warnings.

### CODE REVIEW

**Review by dilinger — APPROVED** [review]

**Comment by masatake** [comment]
> That did not work how I wanted it to work :(

???
Which commit are you talking about?

File: print.c [hunk 1]
```diff
@@ -475,7 +475,9 @@ lkup_port(p, pr, src)
 	MALLOC_S nl;
 	char *nm, *pn;
 	static char pb[128];
+#if	!defined(HASNORPC_H)
 	static int pm = 0;
```
Comment (dilinger) [inline print.c:477]: Instead of having this here and then checking it later to see if we should call fill_portmap(), how about we move that static variable to fill_portmap() and check inside of the function whether or not it should run? I can send a separate patch for that, if you want to remove this part of this commit.

File: arg.c [hunk 2]
```diff
@@ -29,10 +29,8 @@
  * 4. This notice may not be removed or altered.
  */
 
-#ifndef lint
-static char copyright[] =
+volatile static char copyright[] =
```
Comment (dilinger) [inline arg.c:32]: So at least on my local build, gcc strips out this variable from the object file:

dilinger@e7470:/home/dev/lsof$ strings arg.o |grep Copy
dilinger@e7470:/home/dev/lsof$ 

With the standard caveat that I Am Not A Lawyer, the license text says "This notice may not be removed or altered", referring to the comment. The variable is not part of that comment or notice, and the text in the variable is duplicated in the comment. In my opinion, the variable is safe to remove. But I'm fine either way.

Comment (dilinger) [reply arg.c:32]: Oh, I mean that gcc strips it out when the variable is non-volatile. I didn't test it with the volatile keyword added, but it looks okay to me.

**Comment by dilinger** [comment]
> > That did not work how I wanted it to work :(
> 
> ??? Which commit are you talking about?

I was hoping that I could approve commits individually, but instead by clicking "approve" it approved the entire PR.

Other than the fill_portmap thing, it all looks fine.

File: dialects/linux/Makefile [hunk 3]
```diff
@@ -18,7 +18,7 @@ CDEF=
 CDEFS=  ${CDEF} ${CFGF}
 DEP=	${CFGD} ${CFGDN}
 INCL=	${DINC}
-CFLAGS=	${CDEFS} ${INCL} ${DEP} ${DEBUG}
+CFLAGS=	-Wall ${CDEFS} ${INCL} ${DEP} ${DEBUG}
```
Comment (BenBE) [inline dialects/linux/Makefile:21]: Why not put this in the (currently empty) `CDEF` assignment below, which propagates to here anyway?

File: dialects/linux/dsock.c [hunk 4]
```diff
@@ -75,7 +73,7 @@ static char copyright[] =
  * to the same hash backet. This makes seaching the counter part of
  * an end point easier. See get_netpeeri(). */
 #define TCPUDP_IPC_HASH(tp) ((int)(((((tp)->faddr			\
-				      + (tp)->laddr,			\
+				      + (tp)->laddr			\
 				      + (tp)->fport			\
 				      + (tp)->lport			\
 				      + (tp)->proto) * 31415) >> 3)	\
```
Comment (BenBE) [inline dialects/linux/dsock.c:79]: Should use distinct prime factors (large, distinct) to minimize number of collisions. Currently this hash function has obvious collisions that can occur easily.

File: dialects/linux/dsock.c [hunk 5]
```diff
@@ -89,7 +87,7 @@ static char copyright[] =
 	+(int)TCPUDP6_IPC_ADDR_INT32(a, 0x3))
 
 #define TCPUDP6_IPC_HASH(tp) ((int)((((TCPUDP6_IPC_ADDR_MK_INT(&(tp)->faddr) \
-				       + TCPUDP6_IPC_ADDR_MK_INT(&(tp)->laddr), \
+				       + TCPUDP6_IPC_ADDR_MK_INT(&(tp)->laddr) \
 				       + (tp)->fport			\
 				       + (tp)->lport			\
 				       + (tp)->proto) * 31415) >> 3)	\
```
Comment (BenBE) [inline dialects/linux/dsock.c:93]: Same remark as with the above UDP hash.

File: dialects/linux/Makefile (hunk 3 above)
Comment (masatake) [reply dialects/linux/Makefile:21]: I guess the original author introduced CDEF for allowing a user to add extra definition flags (-D) from the command line of make. So I didn't put '-Wall' to CDEF.  Just guessing.

File: dialects/linux/dsock.c (hunk 4 above)
Comment (masatake) [reply dialects/linux/dsock.c:79]: Thank you.
However, in this pull request, I would like to focus on suppressing the warnings reported by the I compiler.
So, could you make a pull request after I merged this pull request?

File: dialects/linux/dsock.c (hunk 5 above)
Comment (masatake) [reply dialects/linux/dsock.c:93]: Thank you.
However, in this pull request, I would like to focus on suppressing the warnings reported by the I compiler.
So, could you make a pull request after I merged this pull request?

File: print.c (hunk 1 above)
Comment (masatake) [reply print.c]: I cherry-picked your change.

File: arg.c (hunk 2 above)
Comment (masatake) [reply arg.c]: I introduced a change for printing the copyright notice to --version output.
Then I introduced another change deleting these variables.

File: dialects/linux/Makefile (hunk 3 above)
Comment (BenBE) [reply dialects/linux/Makefile:21]: The way those variables are handled right now they always override anything provided on the command line. Would have to be `CDEFS?=` to allow overriding by the user.

File: dialects/linux/dsock.c (hunk 4 above)
Comment (BenBE) [reply dialects/linux/dsock.c:75]: Can try to prepare one.

**Review by BenBE — APPROVED** [review]
Changes LGTM (sans hash function as per discussion in comments, PR will follow).

**Comment by masatake** [comment]
@BenBE, thank you for reviewing.

**Review by dilinger — APPROVED** [review]
Looks good!

**Comment by masatake** [comment]
Thank you for revieiwng.
